CREATE DATABASE ZEPTO_PROJECT;
USE ZEPTO_PROJECT;




CREATE TABLE ZEPTO_TABLE(
  CATEGORY VARCHAR(50),
  NAME VARCHAR(120) NOT NULL,
  MRP DECIMAL(10,3),
  DISCOUNTPERCENT INT,
  AVAILABLEQUANTITY DECIMAL(10,3),
  DISCOUNTEDSELLINGPRICE DECIMAL(10,3),
  WEIGHTINGMS DECIMAL(10,3),
  OUTOFSTOCK VARCHAR(10),
  QUANTITY NUMERIC(10,3)
);



-- Display the whole dataset
SELECT * FROM ZEPTO_TABLE;

-- Display the total count of the data.
SELECT COUNT(SKU_ID) FROM ZEPTO_TABLE;

-- Adding an auto-incrementing primary key column as the first column
ALTER TABLE ZEPTO_TABLE ADD COLUMN SKU_ID INT PRIMARY KEY AUTO_INCREMENT FIRST;

-- Check null values in the dataset 
SELECT * FROM ZEPTO_TABLE 
WHERE NAME IS NULL
OR
CATEGORY IS NULL
OR
MRP IS NULL
OR
DISCOUNTPERCENT IS NULL
OR
AVAILABLEQUANTITY IS NULL
OR
DISCOUNTEDSELLINGPRICE IS NULL
OR
WEIGHTINGMS IS NULL
OR
OUTOFSTOCK IS NULL
OR
QUANTITY IS NULL;


-- Different product categories
SELECT DISTINCT(CATEGORY) FROM ZEPTO_TABLE
ORDER BY CATEGORY;


-- Total count of the category
SELECT COUNT(DISTINCT(CATEGORY)) FROM ZEPTO_TABLE;


-- Product in stock vs Out of stock
SELECT OUTOFSTOCK, count(sku_id)
FROM ZEPTO_TABLE
GROUP BY OUTOFSTOCK;


-- Product names present multiple times
SELECT NAME, COUNT(SKU_ID) AS TOTAL_SKU
FROM ZEPTO_TABLE
GROUP BY NAME 
HAVING COUNT(SKU_ID) > 1
ORDER BY COUNT(SKU_ID) DESC;



-- Data cleaning

-- Checking if any product have price "0"
SELECT * FROM 
ZEPTO_TABLE
WHERE MRP = 0 OR DISCOUNTEDSELLINGPRICE = 0 ;

DELETE FROM ZEPTO_TABLE
WHERE MRP = 0;




-- Converting paisa into rupees
UPDATE ZEPTO_TABLE
SET MRP = MRP/100,
DISCOUNTEDSELLINGPRICE = DISCOUNTEDSELLINGPRICE/100;

SELECT MRP, DISCOUNTEDSELLINGPRICE FROM ZEPTO_TABLE;

-- 🧠 Business Intelligence Queries



-- Q1. Find the top 10 best-value products based on the discount percentage.

SELECT NAME,mrp,DISCOUNTPERCENT 
FROM ZEPTO_TABLE
ORDER BY DISCOUNTPERCENT DESC
LIMIT 10;



-- Q2. What are the Products with High MRP but Out of Stock

SELECT DISTINCT(NAME), MRP,OUTOFSTOCK
FROM ZEPTO_TABLE
WHERE OUTOFSTOCK = 'TRUE' AND MRP > 300
ORDER BY MRP DESC;



-- Q3Calculate Estimated Revenue for each category

SELECT CATEGORY,
SUM(DISCOUNTEDSELLINGPRICE*AVAILABLEQUANTITY) AS Total_revenue
FROM ZEPTO_TABLE
GROUP BY CATEGORY
ORDER BY Total_revenue;



-- Q4. Find all products where MRP is greater than 500 and discount is less than 10%

SELECT DISTINCT(NAME),MRP,DISCOUNTPERCENT
FROM ZEPTO_TABLE
WHERE MRP > 500 AND DISCOUNTPERCENT < 10
ORDER BY MRP DESC,DISCOUNTPERCENT DESC;



-- Q5. Identify the top 5 categories offering the highest average discount percentage

SELECT CATEGORY,
round(AVG(DISCOUNTPERCENT),2) AS highest_average_discount_percentage
FROM ZEPTO_TABLE
GROUP BY CATEGORY
ORDER BY highest_average_discount_percentage DESC
LIMIT 5;




-- Q6. Find the price per gram for products above 100g and sort by best value.
SELECT * FROM ZEPTO_TABLE;
SELECT DISTINCT(NAME),WEIGHTINGMS,DISCOUNTEDSELLINGPRICE,
ROUND(DISCOUNTEDSELLINGPRICE / WEIGHTINGMS,2) AS PRICE_PER_GRAM
FROM ZEPTO_TABLE
WHERE WEIGHTINGMS >= 100
ORDER BY PRICE_PER_GRAM ;




-- Q7. Group the products into categories like Low, Medium, Bulk.

SELECT DISTINCT(NAME), WEIGHTINGMS,
CASE WHEN WEIGHTINGMS < 1000 THEN 'LOW'
     WHEN WEIGHTINGMS < 5000 THEN 'MEDIUM'
     ELSE 'BULK'
     END AS WEIGHT_CATEGORY
FROM ZEPTO_TABLE
ORDER BY WEIGHT_CATEGORY;



-- Q8. What is the Total Inventory Weight Per Category
SELECT * FROM ZEPTO_TABLE;
SELECT DISTINCT(CATEGORY),ROUND(SUM(WEIGHTINGMS * AVAILABLEQUANTITY),2) AS TOTAL_WEIGHTS
FROM ZEPTO_TABLE
GROUP BY CATEGORY
ORDER BY TOTAL_WEIGHTS;




-- EXTRA WORK / Changing Table structure Using Alter 
ALTER TABLE ZEPTO_TABLE MODIFY COLUMN MRP DECIMAL(10,2);
ALTER TABLE ZEPTO_TABLE MODIFY COLUMN DISCOUNTEDSELLINGPRICE DECIMAL(10,2);


------------------------------  Completed -------------------------------------------














